### ISSUE TITLE
 Response code 400 (undefined)

### ISSUE THREAD

**Issue by vijayamin83** [apidaze/sdk-node#35]
**Error**

{ HTTPError: Response code 400 (undefined)
    at EventEmitter.emitter.on (/node_modules/got/dist/source/as-promise.js:118:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError' }

**Code**
const { Apidaze } = require('apidaze');

const API_KEY = "xxxxxx";
const API_SECRET = "xxxxxxxxxxxxxxxxxxxxxx";

const ApidazeClient = new Apidaze(API_KEY, API_SECRET);

(async () => {
  // create a user
  try{
  const { body: createdUser } = await ApidazeClient.sipUsers.create({
    username: 'sip_account',
    name: 'SIP Account',
    email_address: 'sip@apidaze.io',
    internal_caller_id_number: '1234',
    external_caller_id_number: '123412341234'
  });
  console.log('the created user', createdUser);
}
catch(e){
  console.log(e)
}

  
})();

**Comment by vijayamin83** [comment]
Hi,

Can any one help me on this issue please.

**Comment by jedb4** [comment]
Thanks for your patience.  We identified the bug and updated the repo today.  Please pull the current code and you should have success with these methods.

**Comment by vijayamin83** [comment]
Thanks for the update. I have installed this with "npm install apidaze/sdk-node" and using this in my code like const { Apidaze } = require('apidaze');

but it didn't work same error.

Is there anything I miss or doing wrong, basically I just want to use that code in my lambda

**Comment by barinali** [comment]
@vijayamin83 I wonder if you can share `e.response` from the catch block with us? `response` property in the error object will contain details about what is wrong. That may help us understand what you may be facing.

**Comment by jedb4** [comment]
If you were running this from a local install, the recent fix for the 400 errors may not have been updated unless you manually removed the apidaze node_module.  We have pushed an update for the version in package.json so that npm update will properly modify the files. to the newest.  Otherwise please share `e.response` from a catch block.

**Comment by garvita-solanki** [comment]
Thanks it working now you can close this issue

**Comment by vijayamin83** [comment]
Thanks,
Its working now you can close this issue now
